import type { ComponentData } from '../types'
import { nanoid } from 'nanoid'

/** Generates a short random ID using nanoid (10 characters). */
export function generateId(): string {
  return nanoid(10)
}

/**
 * Ensures `props.id` is set on a component and, recursively, on every child in
 * its slot fields. Useful for importing externally produced trees (e.g. JSON
 * generated by an AI agent) where nested nodes may lack ids.
 *
 * Returns the component unchanged (same reference) when the entire subtree
 * already has ids; otherwise returns a new tree with only the changed nodes
 * replaced.
 */
export function ensureId<T extends ComponentData>(component: T): T {
  let changed = false
  const newProps: Record<string, unknown> = {}

  for (const [key, value] of Object.entries(component.props)) {
    // The only array-typed props are slot fields (see utils/tree.ts).
    if (Array.isArray(value)) {
      const children = value as ComponentData[]
      const newChildren = children.map((child) => {
        const ensured = ensureId(child)
        if (ensured !== child)
          changed = true
        return ensured
      })
      newProps[key] = newChildren
    }
    else {
      newProps[key] = value
    }
  }

  if (!component.props.id) {
    newProps.id = generateId()
    changed = true
  }

  if (!changed)
    return component
  return { ...component, props: newProps } as T
}
